INSERT INTO learningCode.comments (id, commenter_id, commenter, posting_id, comment) VALUES (3, 32, 'd', 7, '알고리즘 좋아요');
INSERT INTO learningCode.comments (id, commenter_id, commenter, posting_id, comment) VALUES (5, 32, 'd', 16, 'sdfaasd');
INSERT INTO learningCode.comments (id, commenter_id, commenter, posting_id, comment) VALUES (7, 32, 'd', 21, 'sadf');
INSERT INTO learningCode.comments (id, commenter_id, commenter, posting_id, comment) VALUES (8, 32, 'd', 7, 'aaaaa');
INSERT INTO learningCode.comments (id, commenter_id, commenter, posting_id, comment) VALUES (9, 28, '김윤기', 38, '트리~~');
INSERT INTO learningCode.comments (id, commenter_id, commenter, posting_id, comment) VALUES (10, 37, '정태웅', 38, 'hi goodjob');
INSERT INTO learningCode.comments (id, commenter_id, commenter, posting_id, comment) VALUES (11, 37, '정태웅', 40, '연락주세요');
INSERT INTO learningCode.comments (id, commenter_id, commenter, posting_id, comment) VALUES (12, 39, '김승기', 43, 'test');
INSERT INTO learningCode.comments (id, commenter_id, commenter, posting_id, comment) VALUES (13, 39, '김승기', 43, 'test');
INSERT INTO learningCode.comments (id, commenter_id, commenter, posting_id, comment) VALUES (14, 39, '김승기', 43, 'test');
INSERT INTO learningCode.comments (id, commenter_id, commenter, posting_id, comment) VALUES (16, 46, 'shchae', 38, '잘 봤습니다');
INSERT INTO learningCode.comments (id, commenter_id, commenter, posting_id, comment) VALUES (17, 48, 'learning', 40, '어떤걸 공부하실 건가요??');